### PR TITLE
Upgrade

### PR DESCRIPTION
**Pull request by tpouyer**
**Description of the change:**
Add upgrade capabilities to deploy repo.

**Motivation for the change:**
Enable upgrade testing for CICD

Issue #6679

### CODE REVIEW

**Comment by tpouyer** [comment]
@gurnben Can I get a review on this?  I'd like to get it merged before additional changes make their way into the repo.

**Comment by gurnben** [comment]
@tpouyer Apologies, this fell off of my radar!  I'll run it through CI now.

**Comment by gurnben** [comment]
@tpouyer tried running this through the canaries and got this error: https://travis-ci.com/github/open-cluster-management/canary/jobs/446008726#L354

resulting from the invocation here: https://github.com/open-cluster-management/canary-scripts/blob/2.2-integration/deploy.sh#L56

Which I bet is caused by this legacy INSTALL_MODE definition that's held over from when we were using the installer tests (and didn't remove due to the intent to re-enable eventually).  

Should we remove that across all active branches and reattempt?

**Comment by tpouyer** [comment]
> @tpouyer tried running this through the canaries and got this error: https://travis-ci.com/github/open-cluster-management/canary/jobs/446008726#L354
> 
> resulting from the invocation here: https://github.com/open-cluster-management/canary-scripts/blob/2.2-integration/deploy.sh#L56
> 
> Which I bet is caused by this legacy INSTALL_MODE definition that's held over from when we were using the installer tests (and didn't remove due to the intent to re-enable eventually).
> 
> Should we remove that across all active branches and reattempt?

@gurnben so there is a legacy `INSTALL_MODE` variable being used in the canary repo somewhere?  I can change the variable used in the deploy repo to another name like `MODE` to avoid the conflict.

**Comment by gurnben** [comment]
@tpouyer Correct, the `INSTALL_MODE` variable is also used by the installer tests, so if we can change that var name I'll re-verify!

**Comment by tpouyer** [comment]
@gurnben Ok, changes made to rename `INSTALL_MODE` to `MODE`... please give this a shot.

**Comment by gurnben** [comment]
@tpouyer here's the output from this run:
https://travis-ci.com/github/open-cluster-management/canary/jobs/447177276#L329-L345

**Comment by tpouyer** [comment]
> @tpouyer here's the output from this run:
> https://travis-ci.com/github/open-cluster-management/canary/jobs/447177276#L329-L345

This looks like it was a connectivity issue and not related to the changes I made?

**Comment by gurnben** [comment]
Potentially, I'll re-test with fresh clusters to verify!

**Review by gurnben — APPROVED** [review]
@tpouyer it looks like the re-run is working (though its hitting our recent issue with the install).  [Here's the travis job.](https://travis-ci.com/github/open-cluster-management/canary/jobs/450923804).  Approving!

**Pull request merged**
