### PR TITLE
Update nuke to remove registration CRDs

### PR DESCRIPTION
**Pull request by mdelder**
**Description of the change:**

The new CRDs that are added by registration-operator are not being cleaned up.

**Motivation for the change:**

### CODE REVIEW

**Comment by gurnben** [comment]
Is there a plan for this to get into the uninstall process @joeg-pro @nathanweatherly?

**Comment by mdelder** [comment]
@gurnben Are you okay to mark this reviewed and we'll add it to the scripted uninstall?

**Comment by gurnben** [comment]
Good question, @TheRealHaoLiu does this conflict with any new changes coming into nuke?

**Comment by joeg-pro** [comment]
@gurnben  Re:
> Is there a plan for this to get into the uninstall process @joeg-pro @nathanweatherly?

No.  registration is packaged as part of the hub operator (and then as part of the ACM operator for the downstream packaging) and so its CRDs get installed by OLM.  Its known (and accepted for other CRDs) that OLM leaves them behind even you uninstall the operator.

**Pull request merged**
