### PR TITLE
update to oc apply -k, should be kubectl apply -k

### PR DESCRIPTION
**Pull request by Randy424**
**Description of the change:**
Updated start.sh script, replacing oc apply -k with kubectl apply -k

**Motivation for the change:**
-k is not a valid flag for "oc apply"

### CODE REVIEW

**Comment by TheRealHaoLiu** [comment]
this depends on your oc version maybe? but i do agree that it should be kubectl

**Comment by TheRealHaoLiu** [comment]
btw if u r making this  change  u should also change it in the delete  as well

**Comment by tpouyer** [comment]
Well, since we officially do not run on any OCP cluster earlier than 4.3 leaving the `oc apply` may not be a bad thing.

**Comment by tpouyer** [comment]
I don't have a strong opinion either way... I'm fine with changing all `oc apply -k` calls to `kubectl apply -k`.

For consistency... @Randy424 can you also change the `uninstall.sh` script at the root of the repo to use `kubectl delete -k`.

**Comment by jnpacker** [comment]
@Randy424 Do you plan to add the version check? Otherwise, please abandon(close) this merge.  Thx.

**Comment by Randy424** [comment]
Yes, sorry I've fallen a bit behind. Will take care of this today.

**Comment by tpouyer** [comment]
I concur with @jnpacker... we should require `oc` >= 4.3

**Comment by jnpacker** [comment]
@Randy424 Just put a message in the else directing them to download the `oc` cli 4.3 or higher, maybe a link if you can find one and `exit 1` the script.

Then we're good.

**Pull request merged**
