### PR TITLE
(2.5) Install MCE Alongside ACM

### PR DESCRIPTION
**Pull request by zkayyali812**
Signed-off-by: Zachary Kayyali <zkayyali@redhat.com>

**Description of the change:**
https://github.com/open-cluster-management/backlog/issues/18536

**Motivation for the change:**
https://github.com/open-cluster-management/backlog/issues/18536

### CODE REVIEW

**Comment by zkayyali812** [comment]
Validated on ACM 2.2.11, 2.3.6, 2.4.2, and 2.5.Z(2.5 validation is done on release-9.9).

Also validated with TARGET_NAMESPACE, SKIP_MCH_INSTALL, and SKIP_OPERATOR_INSTALL

**Review by Kyl-Bempah — APPROVED** [review]
LGTM, validated in Travis on 2.3 & 2.4, @MacdonEm will likely need to update her base image or scripting to accomodate for `wget` and possibly `yq`

**Comment by dhaiducek** [comment]
There are a couple of issues here:
- `wget` is not universally available
- There's an assumption that `~/bin` is in the `PATH`

I'm thinking a safer set of commands (and this doesn't account for system architecture) could be (this is how I accounted for it in my automation scripts):
```shell
curl -sLO https://github.com/mikefarah/yq/releases/download/v4.16.2/yq_linux_amd64.tar.gz -o yq_linux_amd64.tar.gz
tar xzf yq_linux_amd64.tar.gz
chmod +x yq_linux_amd64
mv yq_linux_amd64 /usr/local/bin/yq
rm yq_linux_amd64.tar.gz
```

**Comment by dhaiducek** [comment]
Alternatively (or in addition), we may want to either:
- Abandon use of `yq` in favor of `sed` or a similar utility
- Exit with an error if `yq` isn't found since the install won't work anyway without it (after or instead of attempting to install it)

**Comment by dhaiducek** [comment]
Also, we should announce somewhere (#forum-acm or #team-red-chesterfield) that the `acm-custom-registry` no longer resides in the OCM namespace. I know I have relied on that in the past to quickly get the snapshot of my instance.

**Comment by zkayyali812** [comment]
Currently, we used `yq` for its simplicity here in editing the required files. Currently the script will attempt to detect if `yq` is installed, and download `yq` if it is missing on a canary run.

The above PR updates the deploy script to ensure that ACM can install alongside MCE in the canaries.

I think wed prefer to use yq over sed due to the simplicity in editing the required files, sed does not work well for yaml files and does not function the same across architectures - https://github.com/stolostron/deploy/blob/master/start.sh#L79

As of now, the deploy script will exit if `yq` is not detected, although it will install and proceed with the installation if it is running on a canary - https://github.com/stolostron/deploy/blob/master/start.sh#L79
This can be updated to be a more thorough check, rather than just checking the architecture, if wed like to ensure it fails if `yq` is not installed.

**Comment by zkayyali812** [comment]
The namespace change is due to the fact that subscriptions to catalogsources can only reside in the same namespace of the related catalogsource, or they can subscribe to catalogsources under the `olm` namespace - https://olm.operatorframework.io/docs/tasks/troubleshooting/subscription/#a-subscription-in-namespace-x-cant-install-operators-from-a-catalogsource-in-namespace-y

This change was essentially done to standardize how catalogsources/subscriptions are stood up. Now that we are going to stand up multiple subscriptions, this is required.

**Comment by dhaiducek** [comment]
Thanks for the explanations, @zkayyali812. I've created a followup PR (#225) that I think addresses my remaining concerns. Please take a look when you have a moment.

**Pull request merged**
